version: '3'
services:
  postgres:
    image: postgres:latest
    ports:
      - '${EXPOSED_CONTAINER_TYPEORM_PORT}:${TYPEORM_PORT}'
    environment:
      POSTGRES_PASSWORD: ${TYPEORM_PASSWORD}
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - backend
  redis:
    image: redis:latest
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
        - '${EXPOSED_CONTAINER_REDIS_PORT}:${REDIS_PORT}'
    networks:
      - backend
  node-api-base:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    environment:
      PORT: "${PORT}"
      JWT_SECRET: "${JWT_SECRET}"
      TYPEORM_TYPE: postgres
      TYPEORM_HOST: postgres
      TYPEORM_USERNAME: postgres
      TYPEORM_PASSWORD: postgres
      TYPEORM_DATABASE: "${TYPEORM_DATABASE}"
      TYPEORM_PORT: "${TYPEORM_PORT}"
      TYPEORM_SYNCHRONIZE: "true"
      TYPEORM_LOGGING: "true"
      TYPEORM_MIGRATIONS_RUN: "${TYPEORM_MIGRATIONS_RUN}"
      ACCESS_TOKEN_LIFE: "${ACCESS_TOKEN_LIFE}"
      RATE_LIMIT_WINDOW: "${RATE_LIMIT_WINDOW}"
      RATE_LIMIT_MAX_REQUESTS: "${RATE_LIMIT_MAX_REQUESTS}"
    ports:
      - '${EXPOSED_CONTAINER_SERVER_PORT}:${PORT}'
    restart: on-failure
    container_name: laccpass-orchestrator
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    volumes:
      - "./src:/app/src"
      - /src/node_modules
      - ".env.dev:/app/.env.dev"
    networks:
      - backend
networks:
  backend:
    name: backend
    external: true