# Check out https://hub.docker.com/_/node to select a new base image
FROM node:16.20.0-alpine
WORKDIR /app
COPY ./package.json .
COPY ./yarn.lock .
COPY tsconfig* ./
COPY ormconfig* ./
COPY src ./src
COPY .env* ./
# Uncomment the next line if your laptop has an M1 processor
# RUN apk --no-cache add --virtual builds-deps build-base python
RUN apk add --no-cache git openssh
# adding because of DIDComm
RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*
RUN yarn
EXPOSE 3000
CMD [ "yarn", "dev" ]